# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:

- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji



# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: MPiangerelli # jekyll-seo-tag > Owners twitter username
author: MPiangerelli # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Marco Piangerelli # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/Mpiangerelli
    - https://www.facebook.com/marco.piangerelli
    - https://www.linkedin.com/in/marco-piangerelli-08392768/
    - https://github.com/MPiangerelli
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
#sass:
#  style: compressed # Style compression
#permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
#excerpt_separator: <!-- more --> # Marks end of excerpt in posts
#timezone: Europe/London # Timezone for blog posts and alike

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "unicam_logo_bianco.png" # Default image for sharing

# Site settings
url: 'https://marcopiangerelli.it'
baseurl: 'https://github.com/MPiangerelli/MPiangerelli.github.io/edit/master'
title: 'My website'
description: ''
permalink: pretty
logo: "unicam_logo_bianco.png"



# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Marco Piangerelli" # Site name or title, also used in jekyll-seo-tag
logo: "/unicam_logo_bianco.png" # Site logo, also used in jekyll-seo-tag
description: "Computer Science Division & Math Division, Polo 'Carla Lodovici', via Madonna delle Carceri, 7" # Site description and default description, also used in jekyll-seo-tag
url: "https://marcopiangerelli.it/" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/MPiangerelli/MPiangerelli.github.io"
email: "marco.piangerelli-at-unicam.it"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'


# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Research & Publications
  url: /research/
- title: Teaching
  #url: /teaching/
  url: /teaching1.html
- title: Projects
  url: /projects/
- title: Dissemination
  url: /speaker/
- title: Interests
  url: /interests/
#- title: Lignani
#  url: https://progettolignani.netlify.com
- title: Blog
  url: /blog/
#- title: virtual Blog
#  url: /bolt-opl/index-2.html




# Footer nav
#navigation_footer:
#- title: Back to top
#  url: "#top"
  
navigation_footer:
- title: Adapted from Alembic theme
  url: https://alembic.darn.es/
  
social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/MPiangerelli
  LinkedIn: https://www.linkedin.com/in/marco-piangerelli-08392768/
  GitHub: https://github.com/MPiangerelli
  Orcid: https://orcid.org/0000-0002-8545-3740
  researcherid: https://publons.com/researcher/1938765/marco-piangerelli/
  researchgate: https://www.researchgate.net/profile/Marco_Piangerelli
  #link: https://darn.es
  #RSS: /feed.xml

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: /amalassunta.png
    #"https://picsum.photos/2560/600?image=866"
